version: '3.8'

services:
  api:
    build: .
    container_name: project_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://test_user:test_pass@db/test_database
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis

  worker:
    container_name: project_worker
    build: .
    command: "celery -A app.worker.celery_app worker --loglevel=info"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://test_user:test_pass@db/test_database
      - PYTHONPATH=/app
    depends_on:
      - redis
      - db

  db:
    container_name: project_db
    image: postgres:13
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=test_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: project_redis
    image: redis:6.2-alpine

volumes:
  postgres_data:

